---
title: "ngetes"
author: "Daniel Syahputra"
date: "1/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(shinydashboard)
library(tidyverse)
library(lubridate)
library(scales)
library(echarts4r)
library(highcharter)
library(htmlwidgets)
library(glue)


# Data Preparation
marketing <- read.csv("datasets/marketing_data.csv")

marketing$Income <- parse_number(marketing$Income)
marketing$Dt_Customer <- mdy(marketing$Dt_Customer)

marketing$Education[marketing$Education == "Graduation"] <- "Undergraduate"
marketing$Education[marketing$Education == "2n Cycle"] <- "Master"

status <- c("YOLO", "Alone", "Absurd")
marketing$Marital_Status[marketing$Marital_Status %in% status] <- "Single"

marketing <- marketing %>%
  mutate_if(is.character, as.factor)

average_income <- aggregate(Income ~ Education + Marital_Status, data=marketing, FUN=mean)

imputed_data <- left_join(marketing[is.na(marketing$Income),],
                          average_income,
                          by = c("Education", "Marital_Status"))

imputed_data$Income.x <- imputed_data$Income.y
imputed_data <- imputed_data %>% select(-Income.y)
colnames(imputed_data)[5] <- "Income"

marketing <- full_join(marketing,
                       imputed_data,
                       by = c('ID',
                              'Year_Birth',
                              'Education',
                              'Marital_Status',
                              'Kidhome',
                              'Teenhome',
                              'Dt_Customer',
                              'Recency',
                              'MntWines',
                              'MntFruits',
                              'MntMeatProducts',
                              'MntFishProducts',
                              'MntSweetProducts',
                              'MntGoldProds',
                              'NumDealsPurchases',
                              'NumWebPurchases',
                              'NumCatalogPurchases',
                              'NumStorePurchases',
                              'NumWebVisitsMonth',
                              'AcceptedCmp3',
                              'AcceptedCmp4',
                              'AcceptedCmp5',
                              'AcceptedCmp1',
                              'AcceptedCmp2',
                              'Response',
                              'Complain',
                              'Country'))
marketing <- marketing  %>%
  mutate(Income = coalesce(Income.x, Income.y)) %>%
  select(-c("Income.x", "Income.y"))
```

```{r}
marketing <- marketing %>% 
  mutate(Age = as.integer(format(Sys.Date(), "%Y")) - Year_Birth)

convert_age <- function(age){ 
    if(age >= 58){
      age <- "> Boomers II" 
    }else if(age >= 42){
      age <- "Gen X"
    }else if (age >= 26){
      age <- "Millennials"
    } else {
      age <- "Gen Z"
    }
}

marketing$Era <- sapply(X = marketing$Age, 
                            FUN = convert_age) 
marketing$Era <- as.factor(marketing$Era)
str(marketing)
```

```{r}
colSums(is.na(marketing))
```
```{r}
marketing %>% 
  filter(Income < 0)
```
```{r}
hcoptslang <- getOption("highcharter.lang")
hcoptslang$thousandsSep <- "*"
options(highcharter.lang = hcoptslang)
```


```{r}
valueBoxSpark <- function(value, title, sparkobj = NULL, subtitle, info = NULL, 
                            icon = NULL, color = "aqua", width = 4, href = NULL){
    
    shinydashboard:::validateColor(color)
    
    if (!is.null(icon))
      shinydashboard:::tagAssert(icon, type = "i")
    
    info_icon <- tags$small(
      tags$i(
        class = "fa fa-info-circle fa-lg",
        title = info,
        `data-toggle` = "tooltip",
        style = "color: rgba(255, 255, 255, 0.75);"
      ),
      # bs3 pull-right 
      # bs4 float-right
      class = "pull-right float-right"
    )
    
    boxContent <- div(
      class = paste0("small-box bg-", color),
      div(
        class = "inner",
        tags$small(title),
        if (!is.null(sparkobj)) info_icon,
        h3(value),
        if (!is.null(sparkobj)) sparkobj,
        p(subtitle)
      ),
      # bs3 icon-large
      # bs4 icon
      if (!is.null(icon)) div(class = "icon-large icon", icon, style = "z-index; 0")
    )
    
    if (!is.null(href)) 
      boxContent <- a(href = href, boxContent)
    
    div(
      class = if (!is.null(width)) paste0("col-sm-", width), 
      boxContent
    )
  }
```

```{r}
hcCustomerIncome <- hchart(
      density(marketing$Income),
      type = "area", name = "Income",
      color = "#db902e"
    ) %>% 
      hc_title(text = "Customer's Income") %>% 
      hc_tooltip(crosshairs = TRUE,
                 borderWidth = 2,
                 pointFormat = '<span style="color:{series.color}">{series.name}</span>:
                       <b>${point.x:.4f}</b><br/>')

    vbCustomerIncome <- valueBoxSpark(
      value = dollar(mean(marketing$Income), 
                     prefix = "$", big.mark = ",",
                     decimal.mark = ".", 
                     accuracy = 0.01),
      title = toupper("AVERAGE CUSTOMER INCOME"),
      sparkobj = hcCustomerIncome,
      info = "This is the customer income based on marketing data",
      subtitle = tagList("Customer Income ",
                         HTML("&uarr;"),
                         percent(mean(marketing$Income), 
                                 decimal.mark = ".", 
                                 accuracy = .01)),
      icon = icon("money-bill-wave"),
      color = "teal",
      href = NULL
    )
    
vbCustomerIncome
```

```{r}
max(marketing$Income)
```
```{r}
customerSpent <- marketing %>% 
  select(MntWines, MntFruits, MntMeatProducts, MntFishProducts, MntSweetProducts, MntGoldProds) %>% 
  mutate(TotalSpent = MntWines + MntFruits + MntMeatProducts + 
           MntFishProducts + MntSweetProducts + MntGoldProds)

hchart(
      density(customerSpent$TotalSpent),
      type = "area", name = "Total Spent",
      color = "#db902e"
    ) %>% 
      hc_xAxis(min = 0) %>% 
      hc_title(text = "Customer Total Spent") %>% 
      hc_tooltip(crosshairs = TRUE,
                 borderWidth = 2,
                 pointFormat = '<span style="color:{series.color}">{series.name}</span>:
                       <b>${point.x:.4f}</b><br/>')
```

```{r}
max(customerSpent$TotalSpent)
```
```{r}
customerPurchases <- marketing %>% 
  select(NumWebPurchases, NumCatalogPurchases, NumStorePurchases) %>% 
  mutate(TotalPurchases = NumWebPurchases + NumCatalogPurchases + NumStorePurchases)

hchart(
      density(customerPurchases$TotalPurchases),
      type = "area", name = "Total Purchases",
      color = "#db902e"
    ) %>% 
      hc_xAxis(min = 0,
               color = "#f0f0f0") %>% 
      hc_size(height = 200) %>% 
      hc_title(text = "Customers Total Purchases",
               style = list(color = "#f0f0f0", fontSize =16)) %>% 
      hc_tooltip(crosshairs = TRUE,
                 borderWidth = 2,
                 pointFormat = '<span style="color:{series.color}">{series.name}</span>:
                       <b>{point.x:.1f}</b><br/>')
```
```{r}
mean(customerPurchases$TotalPurchases)
```

```{r}
str(marketing)
```
```{r}
levels(marketing$Education)
```
```{r}
marketing %>% 
      filter(Marital_Status %in% c("Married"),
             Education %in% c("Basic"),
             Era %in% c("Gen X"))
```

```{r}
marketing %>% 
  group_by(Marital_Status) %>% 
  summarise(MeanIncome = mean(Income)) %>% 
  arrange(MeanIncome) %>% 
  e_chart(Marital_Status) %>% 
  e_pie(MeanIncome, radius = c("50%", "75%")) %>% 
  e_theme_custom("marketing_dashboar/www/chart_theme.json") %>% 
  e_title(
    text = "Mean Income by Marital Status",
    left = "center",
    top = "0"
  ) %>% 
  e_legend(F) %>% 
  e_tooltip(
    trigger = "item",
    formatter = JS("
                    function(params){return(
                        '<b>' + params.name + '</b>'
                           + ' : $'
                           + (params.value).toLocaleString('en-US', 
                           {maximumFractionDigits : 2, minimumFractionDigits: 2})
                           )}
                           ")
  )
```
```{r}
marketing %>% 
  mutate(TotalSpent = MntWines + MntFruits + MntMeatProducts + 
           MntFishProducts + MntSweetProducts + MntGoldProds) %>% 
  group_by(Marital_Status) %>% 
  summarise(MeanTotalSpent = mean(TotalSpent)) %>% 
  arrange(desc(MeanTotalSpent)) %>% 
  e_chart(Marital_Status) %>% 
  e_bar(MeanTotalSpent) %>% 
  e_flip_coords() %>% 
  e_y_axis(inverse = T) %>% 
  e_theme_custom("marketing_dashboar/www/chart_theme.json") %>% 
  e_title(
    text = "Mean Total Spent by Marital Status",
    left = "center",
    top = "0"
  ) %>% 
  e_legend(show = F) %>% 
  e_axis_labels(x = "Mean Total Spent") %>% 
  e_x_axis(
    name = "Mean Total Spent",
    nameLocation = "center",
    nameGap = "25",
    formatter = e_axis_formatter(style = c("currency"), currency = "USD")) %>%
  e_tooltip(
    trigger = "item",
    formatter = JS(
      "
       function(params){return(
       '<b>' + params.name + '</b>'
       + ' : $' 
       + params.value[0]
       )}
       "
    )
  )
```
```{r}
getCustomDataCustomers <- function(input, feature) {
    param <- input
    data <- "" 
    if (feature == "Income") {
      if (param == "Marital Status") {
        data <- marketing %>% 
          group_by(Marital_Status)
      } else if (param == "Education") {
        data <- marketing %>% 
          group_by(Education) 
      } else {
        data <- marketing %>% 
          group_by(Era)
      }
      data <- data %>% 
        summarise(MeanIncome = mean(Income)) %>% 
        arrange(MeanIncome)
      return(data)
    } else {
      data <- marketing %>% 
        mutate(TotalSpent = MntWines + MntFruits + MntMeatProducts + 
                 MntFishProducts + MntSweetProducts + MntGoldProds)
      if (param == "Marital Status") {
        data <- data %>% 
          group_by(Marital_Status)
      } else if (param == "Education") {
        data <- data %>% 
          group_by(Education)
      } else {
        data <- data %>% 
          group_by(Era)
      }
      data <- data %>% 
        summarise(MeanTotalSpent = mean(TotalSpent)) %>% 
        arrange(desc(MeanTotalSpent))
      return(data)
    }
    
  }
```

```{r}
getCustomDataCustomers(input = "Education", feature = "Income")
```

```{r}
productSpent <- marketing %>% 
  select(Marital_Status,Education, Era, MntWines, MntFruits, MntMeatProducts,
         MntFishProducts, MntSweetProducts, MntGoldProds)

colnames(productSpent) <- c("Marital_Status", "Education", "Era",
                            "Wines", "Fruits", "Meats", 
                            "Fishs", "Sweets", "Gold")
```

```{r}
productSpent %>% 
  e_charts() %>% 
  e_histogram(Wines) %>% 
  e_theme_custom("marketing_dashboar/www/chart_theme.json") %>% 
  e_title(
    text = "Customers Amount Spent for Wines",
    left = "center",
    top = "0"
  ) %>% 
  e_legend(top = "30") %>% 
  e_axis_labels(x = "Amount Spent") %>% 
  e_x_axis(
    name = "Amount Spent",
    nameLocation = "center",
    nameGap = "25",
    formatter = e_axis_formatter(style = c("currency"), currency = "USD")) %>%
  e_tooltip(
    trigger = "item",
    formatter = JS(
      "
       function(params){return(
       '<b>Freq</b>'
       + ' : ' 
       + params.value[1]
       )}
       "
    )
  )
```


```{r}
productSpent <- productSpent %>% 
  group_by(Marital_Status) %>% 
  summarise(Wines = mean(Wines), 
            Fruits = mean(Fruits),
            Meats = mean(Meats),
            Fishs = mean(Fishs),
            Sweets = mean(Sweets),
            Gold = mean(Gold)) %>% 
  mutate(MeanTotalSpent = Wines + Fruits + Meats + Fishs + Sweets + Gold) %>% 
  arrange(desc(MeanTotalSpent))
```


```{r}
productSpent %>% 
  e_chart(Marital_Status) %>% 
  e_bar(Wines, stack = "grp") %>% 
  e_bar(Fruits, stack = "grp") %>% 
  e_bar(Meats, stack = "grp") %>% 
  e_bar(Fishs, stack = "grp") %>% 
  e_bar(Sweets, stack = "grp") %>% 
  e_bar(Gold, stack = "grp") %>% 
  e_flip_coords() %>% 
  e_y_axis(inverse = T) %>% 
  e_theme_custom("marketing_dashboar/www/chart_theme.json") %>% 
  e_title(
    text = "Mean Total Spent of Each Product",
    left = "center",
    top = "0"
  ) %>% 
  e_legend(top = "30") %>% 
  e_axis_labels(x = "Mean Total Spent") %>% 
  e_x_axis(
    name = "Mean Total Spent",
    nameLocation = "center",
    nameGap = "25",
    formatter = e_axis_formatter(style = c("currency"), currency = "USD")) %>%
  e_tooltip(
    trigger = "item",
    formatter = JS(
      "
       function(params){return(
       '<b>' + params.name + '</b>'
       + ' : $' 
       + params.value[0]
       )}
       "
    )
  )
```

```{r}
```


```{r}
productPurchasesPlatform <- marketing %>% 
  select(MntWines, MntFruits, MntMeatProducts,
         MntFishProducts, MntSweetProducts, MntGoldProds,
         NumWebPurchases, NumCatalogPurchases, NumStorePurchases)

colnames(productPurchasesPlatform) <- 
  c("Wines", "Fruits", "Meats", 
    "Fishs", "Sweets", "Gold",
    "Web", "Catalog", "Store")

# productPurchasesPlatform <- productPurchasesPlatform %>% 
#   pivot_longer(cols = c("Wines", "Fruits", "Meats", 
#                         "Fishs", "Sweets", "Gold"),
#                names_to = "ProductType") %>% 
#   select(-value)
# 
# productPurchasesPlatform %>% 
#   group_by(ProductType) %>% 
#   summarise(Web = mean(Web),
#             Catalog = mean(Catalog),
#             Store = mean(Store))
productPurchasesPlatform
```

```{r}
hcWebPurchases <- hchart(
  density(marketing$NumWebPurchases),
  type = "area",
  name = "Web Purchases",
  color = "#db902e"
) %>% 
  hc_xAxis(min = 0) %>% 
  hc_size(height = 200) %>% 
  hc_title(text = "Web Purchases",
           style = list(color = "#f0f0f0", fontSize =16)) %>% 
  hc_tooltip(borderWidth = 2,
             crosshairs = T,
             pointFormat = '<span style="color:{series.color}">{series.name}</span>:
                       <b>{point.x:.1f}</b><br/>')

vbWebPurchases <- valueBoxSpark(
  value = sum(marketing$NumWebPurchases),
  title = toupper("TOTAL WEB PURCHASES"),
  sparkobj = hcWebPurchases,
  info = "Number of purchases made through the company's website",
  subtitle = NULL,
  icon = icon("store"),
  href = NULL
)
```

```{r}
hcCatalogPurchases <- hchart(
  density(marketing$NumCatalogPurchases),
  type = "area",
  name = "Catalog Purchases",
  color = "#db902e"
) %>% 
  hc_xAxis(min = 0) %>% 
  hc_size(height = 200) %>% 
  hc_title(text = "Catalog Purchases",
           style = list(color = "#f0f0f0", fontSize =16)) %>% 
  hc_tooltip(borderWidth = 2,
             crosshairs = T,
             pointFormat = '<span style="color:{series.color}">{series.name}</span>:
                       <b>{point.x:.1f}</b><br/>')

vbWebPurchases <- valueBoxSpark(
  value = sum(marketing$NumCatalogPurchases),
  title = toupper("TOTAL CATALOG PURCHASES"),
  sparkobj = hcCatalogPurchases,
  info = "Number of purchases made using catalog",
  subtitle = NULL,
  icon = icon("store"),
  href = NULL
)
```

```{r}
hcStorePurchases <- hchart(
      density(marketing$NumStorePurchases),
      type = "area",
      name = "Store Purchases",
      color = "#db902e"
    ) %>% 
      hc_xAxis(min = 0) %>% 
      hc_size(height = 200) %>% 
      hc_title(text = "Store Purchases",
               style = list(color = "#f0f0f0", fontSize =16)) %>% 
      hc_tooltip(borderWidth = 2,
                 crosshairs = T,
                 pointFormat = '<span style="color:{series.color}">{series.name}</span>:
                       <b>{point.x:.1f}</b><br/>')
    
    vbStorePurchases <- valueBoxSpark(
      value = sum(marketing$NumStorePurchases),
      title = toupper("TOTAL STORE PURCHASES"),
      sparkobj = hcStorePurchases,
      info = "Number of purchases made directly in store",
      subtitle = NULL,
      icon = icon("store"),
      href = NULL
    )
    
```

```{r}
platformPurchases <- marketing %>% 
  select(Marital_Status, Education, Era,
         NumWebPurchases, NumCatalogPurchases, NumStorePurchases)

colnames(platformPurchases) <- c("Marital_Status", "Education", "Era",
                                 "Web", "Catalog", "Store")

platformPurchases %>% 
  group_by(Marital_Status) %>% 
  summarise(Web = sum(Web),
            Catalog = sum(Catalog),
            Store = sum(Store)) %>% 
  mutate(TotalPurchases = Web + Store + Catalog) %>% 
  arrange(desc(Web)) %>% 
  e_chart(Marital_Status) %>% 
  e_pie(Web, roseType = "radius") %>% 
  e_theme_custom("marketing_dashboar/www/chart_theme.json") %>% 
  e_title(
        text = glue("Total Purchases on Web"),
        left = "center",
        top = "0"
      ) %>% 
  e_legend(F) %>% 
  e_tooltip(
    trigger = "item",
    formatter = JS("
                function(params){return(
                 '<b>' + params.name + '</b>'
                 + ' : ' 
                 + params.value
                 )}
                       ")
  )

```

```{r}
head(marketing$Country)
```


```{r}
convert_country <- function(country) {
  if (country == "AUS") {
    country <- "Australia"
  } else if (country == "CA") {
    country <- "Canada"
  } else if (country == "GER") {
    country <- "German"
  } else if (country == "IND") {
    country <- "Indonesia"
  } else if (country == "ME") {
    country <- "Mexico"
  } else if (country == "SA") {
    country <- "Saudi Arabia"
  } else if (country == "SP") {
    country <- "Spain"
  } else if (country == "US") {
    country <- "United States"
  } else {
    country <- "Unknown"
  }
}

marketing$CountryName <- sapply(X = marketing$Country, 
                            FUN = convert_country)
marketing$CountryName <- as.factor(marketing$CountryName)
```


```{r}
levels(marketing$CountryName)
```


### Feature Engineering

```{r}
marketing <- marketing %>% 
  mutate(DayEnroll = wday(Dt_Customer, label = T, abbr = F),
         MonthEnroll = month(Dt_Customer, label = T, abbr = F),
         YearEnroll = year(Dt_Customer),
         DayEnroll = as.character(DayEnroll),
         MonthEnroll = as.character(MonthEnroll),
         YearEnroll = as.factor(YearEnroll))

marketing
```
```{r}
campaignData <- marketing %>% 
  select(AcceptedCmp1, AcceptedCmp2, AcceptedCmp3,
         AcceptedCmp4, AcceptedCmp5)

campaignData <- as.data.frame(lapply(campaignData, FUN = mean))
colnames(campaignData) <- c("Campaign 1", "Campaign 2", "Campaign 3",
                            "Campaign 4", "Campaign 5")

campaignData <- campaignData %>% 
  pivot_longer(cols = c("Campaign 1", "Campaign 2", "Campaign 3",
                            "Campaign 4", "Campaign 5"),
               names_to = "CampaignType",
               values_to = "SuccessRate") %>% 
  arrange(desc(SuccessRate)) %>% 
  mutate(SuccessRate = round(SuccessRate * 100, 2))
```

```{r}
campaignData %>% 
  e_chart(CampaignType) %>% 
  e_bar(SuccessRate) %>% 
  e_theme_custom("marketing_dashboar/www/chart_theme.json") %>% 
  e_axis_labels(x = "Campaign Type", y ="Success Rate") %>% 
  e_title(
        text = "Success Rate Each Campaigns",
        left = "center",
        top = "0"
      ) %>% 
      e_legend(F) %>% 
      e_tooltip(
        trigger = "item",
        formatter = JS("
                function(params){return(
                 '<b>' + params.name + '</b>'
                 + ' : ' 
                 + params.value[1] + '%'
                 )}
                       ")
      )
```

```{r}
campaignData <- marketing %>% 
  select(AcceptedCmp1, AcceptedCmp2, AcceptedCmp3,
         AcceptedCmp4, AcceptedCmp5, DayEnroll,
         MonthEnroll, YearEnroll)

colnames(campaignData) <-  c("Campaign 1", "Campaign 2", "Campaign 3",
                                "Campaign 4", "Campaign 5", "Day", "Month", "Year")

campaignData <- campaignData %>% 
  group_by(Day) %>% 
  summarise(Campaign1 = sum(`Campaign 1`),
            Campaign2 = sum(`Campaign 2`),
            Campaign3 = sum(`Campaign 3`),
            Campaign4 = sum(`Campaign 4`),
            Campaign5 = sum(`Campaign 5`))
```

```{r}
campaignData %>% 
  e_chart(Day) %>% 
  e_bar(Campaign1, stack = "grp") %>% 
  e_bar(Campaign2, stack = "grp") %>%
  e_bar(Campaign3, stack = "grp") %>%
  e_bar(Campaign4, stack = "grp") %>%
  e_bar(Campaign5, stack = "grp") %>%
  e_theme_custom("marketing_dashboar/www/chart_theme.json")
```


```{r}
campaignData$Day <- as.character(campaignData$Day)
campaignData
```


```{r}
df <- data.frame(
  x = c(
    rnorm(100),
    runif(100, -5, 10),
    rnorm(100, 10, 3)
  ),
  grp = c(
    rep(LETTERS[1], 100),
    rep(LETTERS[2], 100),
    rep(LETTERS[3], 100)
  )
)

df |> 
  group_by(grp) |> 
  e_charts() |> 
  e_boxplot(x)
```


```{r}
productSpent <- marketing %>% 
      select(Marital_Status,Education, Era,CountryName, MntWines, MntFruits, MntMeatProducts,
             MntFishProducts, MntSweetProducts, MntGoldProds)
    
colnames(productSpent) <- c("Marital_Status", "Education", "Era", "Country",
                                "Wines", "Fruits", "Meats", 
                                "Fishs", "Sweets", "Gold")
    
productSpent
```

```{r}
hc <- hcboxplot(
  x = productSpent$Wines,
  var = productSpent$Marital_Status,
  outliers = TRUE,
  color = "#2980b9"
  ) %>% 
  hc_chart(type = "column")
hc
```


```{r}

RFM <- marketing %>%
  mutate(Monetary = MntWines + MntFruits + MntMeatProducts +
           MntFishProducts + MntSweetProducts + MntGoldProds,
         Frequency = NumWebPurchases + NumCatalogPurchases + NumStorePurchases) %>% 
  select(Recency, Frequency, Monetary)

RFM_table <- RFM %>% 
  pivot_longer(cols = c("Recency", "Frequency", "Monetary"),
               names_to = "Category",
               values_to = "Value")

RFM_table %>% 
  group_by(Category) %>% 
  e_charts() %>% 
  e_boxplot(Value)
```

```{r}
#Scoring
#R_score
RFM$R_Score[RFM$Recency > 74.0] <- 1
RFM$R_Score[RFM$Recency > 49 & RFM$Recency<=74 ] <- 2
RFM$R_Score[RFM$Recency > 24 & RFM$Recency<=49 ] <- 3
RFM$R_Score[RFM$Recency <= 24] <- 4
#F_score
RFM$F_Score[RFM$Frequency < 6]<-1
RFM$F_Score[RFM$Frequency >= 6 & RFM$Frequency < 12] <- 2
RFM$F_Score[RFM$Frequency >= 12 & RFM$Frequency < 18] <- 3
RFM$F_Score[RFM$Frequency >= 18] <- 4
#M_score
RFM$M_Score[RFM$Monetary < 68.75] <-1
RFM$M_Score[RFM$Monetary >= 68.75 & RFM$Monetary < 396.0] <- 2
RFM$M_Score[RFM$Monetary >= 396.0 & RFM$Monetary < 1045.50 ] <- 3
RFM$M_Score[RFM$Monetary >= 1045.50] <- 4

#RFM_score
RFM<- RFM %>% mutate(RFM_Score = 100 * R_Score + 10 * F_Score + M_Score)
```

```{r}
head(RFM)
```


```{r}
#Customer Segmentation
champions <- c(444)
loyal_customers <- c(334, 342, 343, 344, 433, 434, 443)
potential_loyalist <- c(332,333,341,412,413,414,431,432,441,442,421,422,423,424)
recent_customers <- c(411)
promising <- c(311, 312, 313, 331)
needing_attention <- c(212,213,214,231,232,233,241,314,321,322,323,324)
about_to_sleep <- c(211)
at_risk <- c(112,113,114,131,132,133,142,124,123,122,121,224,223,222,221)
cant_lose <- c(134,143,144,234,242,243,244)
hibernating <- c(141)
lost <- c(111)

convert_score <- function(score) {
  if (score %in% champions) {
    score <- "Champions"
  } else if (score %in% loyal_customers) {
    score <- "Loyal Customers"
  } else if (score %in% potential_loyalist) {
    score <- "Potential Loyalist"
  } else if (score %in% recent_customers) {
    score <- "Recent Customers"
  } else if (score %in% promising) {
    score <- "Promising"
  } else if (score %in% needing_attention) {
    score <- "Customer Needing Attention"
  } else if (score %in% about_to_sleep) {
    score <- "About to Sleep"
  } else if (score %in% at_risk) {
    score <- "At risk"
  } else if (score %in% cant_lose) {
    score <- "Can't Lose Them"
  } else if (score %in% hibernating) {
    score <- "Hibernating"
  } else if (score %in% lost) {
    score <- "Lost"
  } else {
    score <- "Unknown"
  }
}

RFM$Segment <- sapply(X = RFM$RFM_Score, FUN = convert_score)

```

```{r}
customerSegmentation <- RFM %>%
      group_by(Segment) %>% 
      summarise(Freq = n()) %>% 
      arrange(desc(Freq))
    
    # Create chart of customer segmentation
    customerSegmentation %>% 
      e_chart(Segment) %>% 
      e_bar(Freq) %>% 
      e_theme_custom("marketing_dashboar/www/chart_theme.json") %>% 
      e_title(
        text = glue("Customer Segmentation"),
        left = "center",
        top = "0"
      ) %>% 
      e_legend(show = F) %>% 
      e_axis_labels(x = "Count") %>% 
      e_x_axis(
        name = "Count",
        nameLocation = "center",
        nameGap = "25") %>%
      e_tooltip(
        trigger = "item",
        formatter = JS(
          "
       function(params){return(
       '<b>' + param.name + '</b>'
       '<b>Count</b>'
       + ' : ' 
       + params.value[0]
       )}
       "
        )
      )
    
```




